/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busqueda;

import Datos.DatosDesordenados;
import Datos.DatosOrdenados;
import javax.swing.JOptionPane;

/**
 *
 * @author Israel
 */
public class PruebaBusqueda extends javax.swing.JFrame {

    /**
     * Creates new form PruebaBusqueda
     */
    public PruebaBusqueda() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Métodos de búsqueda");

        jButton1.setText("generer datos");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setEditable(false);
        jTextArea1.setVisible(false);
        jScrollPane1.setViewportView(jTextArea1);

        jButton2.setText("Buscar");
        jButton2.setVisible(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setVisible(false);
        jTextArea2.setEditable(false);
        jScrollPane2.setViewportView(jTextArea2);

        jLabel3.setText("Datos Ordenados");
        jLabel3.setVisible(false);

        jButton3.setText("Buscar");
        jButton3.setVisible(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Datos DesOrdenados");
        jLabel4.setVisible(false);

        jTextArea4.setColumns(20);
        jTextArea4.setRows(5);
        jTextArea4.setVisible(false);
        jTextArea4.setEditable(false);
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(18, 18, 18)
                            .addComponent(jButton1))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addComponent(jButton3)
                            .addGap(17, 17, 17)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton2)))))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jLabel1)
                        .addContainerGap(812, Short.MAX_VALUE))
                    .addComponent(jScrollPane1)
                    .addComponent(jScrollPane4)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jButton1)
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    static String cad1="",cad2="";
    static int lim=1000,n=20;
    DatosDesordenados datos= new DatosDesordenados(lim,n);
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        jTextArea2.setVisible(true);
        int clave=Integer.parseInt(JOptionPane.showInputDialog("¿Que dato desea buscar?"));
        DatosOrdenados datosOr= datos.mergeSort();
        int menor1=datos.minimo(),mayor1=datos.maximo();
        
        cad1="DesOrdenados\n--> "
            + "Menor="+menor1+"\tPosicion= "+datos.busquedaSecuencial(menor1)+datos.ciclosBS()
            +"\n--> Mayor="+mayor1+"\tPosicion= "+datos.busquedaSecuencial(mayor1)+datos.ciclosBS()
            +"\n--> Clave="+clave+"\tPosicion= "+datos.busquedaSecuencial(clave)+datos.ciclosBS()
            +"\n-->(No existente en lista)Numero="+(clave+10)+"\tPosicion= "+datos.busquedaSecuencial(clave+10)
                +datosOr.ciclosBS();
        jTextArea2.setText(cad1);
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jTextArea4.setVisible(true);
        int clave=Integer.parseInt(JOptionPane.showInputDialog("¿Que dato desea buscar?"));
        DatosOrdenados datosOr= datos.mergeSort();
        int menor=datosOr.minimo(),mayor=datosOr.maximo();
        cad2="Ordenados\n--> "
            + "Menor="+menor+"\tPosicion= "+datosOr.busquedaSecuencial(menor)+datosOr.ciclosBS()
            +"\n--> Mayor="+mayor+"\tPosicion= "+datosOr.busquedaSecuencial(mayor)+datosOr.ciclosBS()
            +"\n--> Clave="+clave+"\tPosicion= "+datosOr.busquedaSecuencial(clave)+datosOr.ciclosBS()
            +"\n-->(No existente en lista)Numero="+(clave+10)+"\tPosicion= "+datosOr.busquedaSecuencial(clave+10)
                +datosOr.ciclosBS()+"\nOrdenados\n--> "
            + "Menor="+menor+"\tPosicion= "+datosOr.busquedaBinaria(menor)+datosOr.ciclosBS()
            +"\n--> Mayor="+mayor+"\tPosicion= "+datosOr.busquedaBinaria(mayor)+datosOr.ciclosBS()
            +"\n--> Clave="+clave+"\tPosicion= "+datosOr.busquedaBinaria(clave)+datosOr.ciclosBS()
            +"\n-->(No existente en lista)Numero="+(clave+10)+"\tPosicion= "+datosOr.busquedaBinaria(clave+10)
                +datosOr.ciclosBS();
        jTextArea4.setText(cad2);
        
    }//GEN-LAST:event_jButton3ActionPerformed
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        jTextArea1.setVisible(true);
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jButton2.setVisible(true);
        jButton3.setVisible(true);
        datos.generarValores();
        DatosOrdenados datosOr= datos.mergeSort();
        jTextArea1.setText("DesOrdenados ---> "+ datos+
                "\n\nOrdenados ---> "+ datosOr);
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PruebaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PruebaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PruebaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PruebaBusqueda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PruebaBusqueda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea4;
    // End of variables declaration//GEN-END:variables
}
